### ISSUE TITLE
Video needs to be re-recorded

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/hello-world-ruby#36]
Video starts by showing the user to fork & clone. This is not the workflow we'll be recommending to users on the qualifying track. Instead, they will be told to use the open button, then learn CLI. We should be showing them how to use the workflow they are already familiar with. 

cc @AnnJohn

**Comment by matbalez-zz** [comment]
Video should also use the learn submit command rather than git commands + PR.

**Comment by aviflombaum** [comment]
I removed the video in 2e092b5 and cleaned up some of the workflow language.
