### ISSUE TITLE
Getting this error over and over... any hints?

### ISSUE THREAD

**Issue by eaud** [learn-co-curriculum/hello-world-ruby#45]
<img width="591" alt="screen shot 2015-10-29 at 12 40 15 pm" src="https://cloud.githubusercontent.com/assets/14064089/10825201/4fe90c2a-7e3a-11e5-9126-9ca90ecf89e1.png">

**Comment by sammarcus** [comment]
Hi @eaud , did you get this figured out? In the future the quickest way to get immediate help in realtime is to click Ask New Question directly on Learn. Sorry about the trouble!

**Comment by eaud** [comment]
Thanks Sam - i did get it sorted, with help under Ask New Question
