### ISSUE TITLE
Please waive this_Ruby eddor

### ISSUE THREAD

**Issue by ndy856** [learn-co-curriculum/hello-world-ruby#55]
![capture](https://cloud.githubusercontent.com/assets/16307930/12011837/6724a092-acad-11e5-9102-03d1cb2f3961.JPG)
this keeps failing but all the steps were performed right.

**Comment by AnnJohn** [comment]
Hi @ndy856 it looks like the tests might still be failing and the solution isn't correct. Again, if you use the Ask a Question tool in Learn someone from our support team will help you out right away. Thanks!
