### ISSUE TITLE
Learn shows not local test passing, but the test passed.

### ISSUE THREAD

**Issue by rachelwatson1** [learn-co-curriculum/hello-world-ruby#56]
I have followed the instructions and my code passed the test.  I was also able to push my code to Github, but Learn shows I still need to pass the local test and it will not allow me to move on.  What is wrong?

**Comment by AnnJohn** [comment]
Hi @rachelwatson1 this is a technical issue so could you please file a bug report. If you hover over your profile pic in Learn a menu will pop up and you'll see an option to file a bug report.  

You can also use the Ask a Question tool in Learn and someone from our Learn Expert team will get back to you.
