### ISSUE TITLE
Voice and style in README

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/hello-world-ruby#58]
This README uses a lot of second-person commands. It should be revised to follow Flatiron's guidelines more closely.

**Comment by AnnJohn** [comment]
changed it somewhat, but kept much of the second person. closing for now.

**Comment by cjbrock** [comment]
Trying to re-open the issue, then close it again, to see if it will remove it from the list on learn.co/curriculum

**Comment by cjbrock** [comment]
Closing it.
