### ISSUE TITLE
crucial instruction missing

### ISSUE THREAD

**Issue by xotrmusic** [learn-co-curriculum/hello-world-ruby#59]
In between the "CREATING A FILE" paragraph and the "WRITING CODE" paragraph, there is no description of how to actually open and edit the hello_world.rb file the user has just created.

Reference to the Sublime Text simlink is moot, since subl command is not found in Learn IDE and permission to install is denied.

pls forgive my english, I'm brand new at this.

**Comment by NYCLondon** [comment]
I noticed this too. The instructions don't provide adequate instructions to perform the task. 

Oh and I have a masters degree in English and a minor in philosophy, and even i can't understand this paragraph!! It's not an English language barrier, the paragraph makes no sense.

**Comment by aviflombaum** [comment]
@NYCLondon @xotrmusic How do you feel about this new language? https://github.com/learn-co-curriculum/hello-world-ruby/commit/81865e9ef51a103c4ee31a5697a614a4bc4b3b77
