### ISSUE TITLE
toolbar disappeared in editor. 

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/hello-world-ruby#64]
instruction is: 
Get started by opening this lab with `learn open` or by clicking the Open button in the toolbar. 

problem 
no toolbar
![untitled](https://cloud.githubusercontent.com/assets/19511967/16359714/474a4146-3b05-11e6-8a1b-532dc1ed72e9.png)

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the _content_ of this lesson. If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by AnnJohn** [comment]
we updated the instruction so that it no longer says toolbar and instead refers to Learn. Thanks!
