### ISSUE TITLE
Green means go, gray means wait for Learn to give me a fix? :)

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/hello-world-ruby#69]
I have been completing, successfully, labs, yet the lesson itself never gives me green. It's been a couple days since I completed the first practice lab. Still no status change. My profile shows that I am NOT in the Intro To Ruby track, yet my current track _is_ the Ruby track -- and my activity shows that I have forked labs and submitted PRs in the track. It also states my current track is the Code Club. Please help! 

Edit: Using Windows with Chrome. And the Learn IDE. :)

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
