### ISSUE TITLE
Error Cloning Lesson

### ISSUE THREAD

**Issue by marcellobonatto** [learn-co-curriculum/hello-world-ruby#73]
When I click on OPEN to load the Hello World lesson - this appears:

Forking lesson...  
Cloning lesson...  
There was a problem cloning this lesson. Retrying...

**Comment by AnnJohn** [comment]
hi @marcellobonatto sorry for the delay. If this is still an issue, please use the Ask a Question tool so that someone from our team can help you right away. We use this space specifically for issues related to curriculum content. Thanks!
