### ISSUE TITLE
Completed hello world lab but learn still asking me to fork depository 

### ISSUE THREAD

**Issue by derek-silva** [learn-co-curriculum/hello-world-ruby#85]
Hello

I completed the Hello World Ruby Lab today and Learn.co is still asking for me to fork the lab. I have already forked the lab, created the ruby file, printed "Hello World!" to the console and learn submit.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.). If Learn is misbehaving, please direct your bug report to bugs@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
