### ISSUE TITLE
Unable to create file

### ISSUE THREAD

**Issue by aliaziz00** [learn-co-curriculum/hello-world-ruby#86]
Hi,

I am unable to create a new file in the IDE. When clicking 'Create new' and selecting 'file' it asks me what I would like the name to be and once I click 'create' the file is not created.

having refreshed the page nothing has changed.

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like an improvement to the Learn platform.
[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum itself (doesn't work, throws a Ruby error, etc.) If Learn is misbehaving, please direct your bug report to bugs@learn.co.

Engineer Note: This issue may be related to a [currently filed bug](https://flatiron.atlassian.net/browse/LABSBOARD-938).

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can, and we will try to discern a proper path to resolution.
