### ISSUE TITLE
I can't open Learn IDE

### ISSUE THREAD

**Issue by hashdotlee** [learn-co-curriculum/hello-world-ruby#87]
I click that button but the page not appear anything else

**Comment by cjbrock** [comment]
Hi @hasuki!

Github issues are actually a place to report issues with the curriculum, not places ask for help with the IDE. That's no problem though! Go ahead and hit the Ask A
Question button on learn.co. Either a community member or a technical coach
will be able to help you understand this stuff.

// <3 Corinna
