### ISSUE TITLE
learn IDE not opening

### ISSUE THREAD

**Issue by Riyuzak2510** [learn-co-curriculum/hello-world-ruby#88]
On clicking the open ide button nothing seems to happen. Need help new to this .

**Comment by morgvanny** [comment]
Hello! This sounds like an issue happening on the learn.co site itself. In that case I think it's best to use the Ask a Question feature on the upper right side of the page, and a Technical Coach should be able to help troubleshoot and resolve the issue quickly. Best of luck, to you!
