### ISSUE TITLE
Solving the exercise outside the learn IDE

### ISSUE THREAD

**Issue by rnrnshn** [learn-co-curriculum/hello-world-ruby#89]
I dont  have my laptop now and I am using my cousin´s computer and I cannot install the IDE. I am using coder,com to study. I would like to know whether i can use it or not. How I can configure tests on coder.com

**Comment by drakeltheryuujin** [comment]
Hi @0limpi0,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum. This sounds like an environment issue, which we unfortunately do not have the capacity to support at this time. I would recommend the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure something out.

I'm sorry, and good luck! 💙
