### ISSUE TITLE
how do i open learn ide

### ISSUE THREAD

**Issue by Footeo** [learn-co-curriculum/hello-world-ruby#92]

**Comment by Footeo** [comment]
The learn IDE won't open when i click it, but the installed one on my computer opens with no problem, I can't get past the hello world lesson in ruby because of this and it's very frustrating.

**Comment by drakeltheryuujin** [comment]
Hi @Footeo! 

This request sounds like there's a problem with the Learn platform. Our product team can help you with this. You can reach them at support@learn.co. [Raising issues on GitHub][raise], like you've done here should happen when there are problems with the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can to clarify our error, and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
