### ISSUE TITLE
LEARN IDE Issue 

### ISSUE THREAD

**Issue by Naja2019** [learn-co-curriculum/hello-world-ruby#93]
Hello,
I have been getting this message from IDE 
"WARNING: You are attempting to open a lesson that is beyond your current lesson.
Are you sure you want to continue? [Y/n]:"
I am currently on the 'Tic tac Toe' lesson

**Comment by sgharms** [comment]
This means that a previous lesson was not marked complete. Navigate to the lesson that you either didn't mark as read or submit a solution for and this warning will go away.

If you need help, try discussing your issue via the [Ask a Question][AAQ] tool. 

[AAQ]: http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson
