### ISSUE TITLE
Learn IDE is not connecting to server

### ISSUE THREAD

**Issue by csilva1** [learn-co-curriculum/hello-world-ruby#94]
My Learn IDE for some reason is not connecting to the server, i keep clicking to reconnect but that doesn't work, i've tried a different wifi just incase it had to do with a firewall but that led me no where. Please help!!!

**Comment by drakeltheryuujin** [comment]
Hi @csilva1! 

This request sounds like a problem with the Learn platform.
Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
