### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Tatyadevotchka** [learn-co-curriculum/hello-world-ruby#96]
The tab "Open IDE" will not open for me in Learn and I'm not sure if I can write the code on Git or if there is a way to fix IDE. Thank you!

**Comment by drakeltheryuujin** [comment]
Hi @Tatyadevotchka! 

This request sounds like a problem with the Learn platform.
Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
